services:
  app: 
    build: .
    container_name: rate-limiter-app
    ports:
      - "6000:6000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"




